<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataExcel</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c892e4e7-2267-427d-91fd-ab21e06c24a6</testSuiteGuid>
   <testCaseLink>
      <guid>ec660231-b3c2-4402-be77-b1c97193ebb5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Form/Form</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>21620cf6-94ad-43b4-8cf3-38a89b614d3c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Excel/BaseExcel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b8f2f86-27cb-483b-ac88-c74c7aafb56f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>21620cf6-94ad-43b4-8cf3-38a89b614d3c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Nombre</value>
         <variableId>23147320-b1d5-405a-b490-453d11f3eec4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>21620cf6-94ad-43b4-8cf3-38a89b614d3c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Apellido</value>
         <variableId>87cd661b-952e-4567-a68a-8da8edff87a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>21620cf6-94ad-43b4-8cf3-38a89b614d3c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>1c766fa5-f26c-4a55-b575-543cbb7d82dd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
