<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataInternal</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0748d4ee-e7bf-4dc5-8c58-d65f234d7f02</testSuiteGuid>
   <testCaseLink>
      <guid>0a071dea-ac30-47b2-a7e8-0046afe0b51d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Form/Form</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>58e2cd63-f519-4c3e-9495-2008fad7c672</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataInternal/DataInternal</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b8f2f86-27cb-483b-ac88-c74c7aafb56f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>58e2cd63-f519-4c3e-9495-2008fad7c672</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Nombre</value>
         <variableId>23147320-b1d5-405a-b490-453d11f3eec4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>58e2cd63-f519-4c3e-9495-2008fad7c672</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Apellido</value>
         <variableId>87cd661b-952e-4567-a68a-8da8edff87a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>58e2cd63-f519-4c3e-9495-2008fad7c672</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>1c766fa5-f26c-4a55-b575-543cbb7d82dd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
