<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Current Address_currentAddress</name>
   <tag></tag>
   <elementGuidId>c6929bfa-9398-474a-a200-8bfc4604a45c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='currentAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#currentAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1c3dcef9-9f40-4d20-8070-72e33eaf3c3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Current Address</value>
      <webElementGuid>5c2f7e57-2058-4a70-9bca-3f8c84bae378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>99a956da-ee85-4e23-8de7-484a964ad3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f3b495e4-69dd-4893-9b6e-e05d91f7389a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentAddress</value>
      <webElementGuid>f6669391-bb9c-4dec-a5d3-1c5a62aa4425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c8a68d63-8f58-4d20-a5b7-3db47f10c95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currentAddress&quot;)</value>
      <webElementGuid>2bbd32d2-82c2-4e46-9a1f-85acb20a1e17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='currentAddress']</value>
      <webElementGuid>88807d27-822b-4f48-b2f9-8c09b50e8331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currentAddress-wrapper']/div[2]/textarea</value>
      <webElementGuid>286ef973-8958-440b-9bb6-111d408afc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>174fe575-21b2-42b2-bbc0-c3eeb269c7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Current Address' and @id = 'currentAddress']</value>
      <webElementGuid>5fdfed74-3e7d-4685-bb7a-8a9cd5f9806c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
