<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What type is it_filetype</name>
   <tag></tag>
   <elementGuidId>75be909d-50dd-41e0-bfdc-17982b7175c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#itsanimage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='itsanimage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1690b153-0191-468d-a1d8-42b8fb67f7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d62e3f18-af24-4cf1-a928-5c4672fec530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>itsanimage</value>
      <webElementGuid>7f34ae8d-e37b-45e3-8e89-0a86fc62752c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>filetype</value>
      <webElementGuid>e3eccf40-b0d4-4d0b-afa7-3d379c780a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>643d2f7e-02db-4beb-aaba-5c28f4eb0b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;itsanimage&quot;)</value>
      <webElementGuid>b79149b9-0cca-4c2e-8008-9caecefa5ee7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='itsanimage']</value>
      <webElementGuid>e8dc38ce-fd9e-41d8-b77c-133a53dc3958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c5227e80-6323-4e14-9353-5546e609efbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'itsanimage' and @name = 'filetype']</value>
      <webElementGuid>52648ed4-bf6d-4b9e-a04e-69f6a876fc26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
