<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apellidos_field_22</name>
   <tag></tag>
   <elementGuidId>eb83bca3-9f15-4157-9329-83008f8bc4aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wsf-1-field-22']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-22</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d90e614-d75a-4f24-89a6-612afe7f2e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45342bd9-398b-4a6a-ba21-91bc4195dd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-22</value>
      <webElementGuid>ea4f8278-609a-4811-b43a-241d4c1b6041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_22</value>
      <webElementGuid>7eac5aef-001d-4fe2-8431-25a87ed72923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellidos</value>
      <webElementGuid>08760042-e5d2-4188-84cd-9dbc4527dce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field</value>
      <webElementGuid>07c9ed20-dd51-4939-a681-5855f499d883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-22</value>
      <webElementGuid>f9223d2e-9bd2-4bfc-b9a7-270efbec8bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-22&quot;)</value>
      <webElementGuid>40bd8af4-870f-4a95-9792-504ed45ca3b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wsf-1-field-22']</value>
      <webElementGuid>e0e11fb1-0577-4294-9093-9ba823285c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-22']/input</value>
      <webElementGuid>e37205fa-9683-4eb7-a723-d62dbd8a93a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e27359dd-761a-46d2-9a0c-2d0bd0248e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'wsf-1-field-22' and @name = 'field_22' and @placeholder = 'Apellidos']</value>
      <webElementGuid>1a1f2857-c02b-4955-9f97-c6f817bd5132</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
