<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Direccin_field_28</name>
   <tag></tag>
   <elementGuidId>fc0caf41-b110-4408-b6fa-58c54a36237e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='wsf-1-field-28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wsf-1-field-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b9ecff65-ad48-4f88-9287-af4771835a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wsf-1-field-28</value>
      <webElementGuid>de087098-238d-44aa-a3aa-612552e0160b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>field_28</value>
      <webElementGuid>ed3d0e2e-08c3-4ea2-af2d-44c93e5ce00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>bd7720aa-a67e-4ae5-bf6f-3be62e5d50f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-textarea-toolbar</name>
      <type>Main</type>
      <value>full</value>
      <webElementGuid>c32710d0-b3be-4c1c-8da4-879ea321bac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsf-field</value>
      <webElementGuid>3d856c13-3809-4403-9ab7-f13e2438febc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>wsf-1-help-28</value>
      <webElementGuid>f51a620b-2114-4053-b83f-5f6ed33368c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>wsf-1-label-28</value>
      <webElementGuid>db7914db-5184-4135-bea7-da11f483ead6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wsf-1-field-28&quot;)</value>
      <webElementGuid>0370c601-e107-4170-a5e1-e1b935b6f878</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='wsf-1-field-28']</value>
      <webElementGuid>cd4c5b57-741e-4513-a0d3-698cd03e1d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wsf-1-field-wrapper-28']/textarea</value>
      <webElementGuid>785da910-c1d4-4c12-a675-16a7017f7a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>acfe4c9f-9be4-4429-9537-a5e9bed7249a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'wsf-1-field-28' and @name = 'field_28' and @placeholder = 'Email']</value>
      <webElementGuid>e6c5896c-ac57-4aef-ae40-e4dad393232e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
